### ISSUE TITLE
Make speedup subfolder the default and only discogs-xml2db mechanism

### ISSUE THREAD

**Issue by ijabz** [philipmat/discogs-xml2db#100]
The speedup approach is so much faster then the original approach we should really scrap the original approach and move speedup to top level. Its work fine with postgres and mysql, the only issue is the import part for Mongodb and Couch is incomplete.

**Comment by philipmat** [comment]
Would it be acceptable to tag (or branch) the current version, make the speedup the default, and direct the Mongo and Couch users to the "legacy" version, at least until we get the Mongo up-to-date too?

**Comment by ijabz** [comment]
I think so, in fact if you read the latest version of https://github.com/philipmat/discogs-xml2db/blob/master/speedup/README.md mongodb should work, but hasnt been tried.
