### ISSUE TITLE
Use python virtual environment over sudo

### ISSUE THREAD

**Issue by philipmat** [philipmat/discogs-xml2db#119]
The README recommends using `sudo` to install modules. It would be safer and easier to use python environments. 

The modules could then be installed without the need to run as root or have elevated permissions.

**Comment by ijabz** [comment]
Not sure I agree this helps.
My problems with Python were not that I need to run multiple different environments, my version of Linux was simply to old to easily update to the required version of Python, e.g. few program that work with 3.4.3 will fail if update to 3.6.9 

If you need to install newer version of python then you'll need to have elevated permissions anyway.

**Comment by philipmat** [comment]
@ijabz - it helps on machines that meet the minimum 3.6 requirement because it no longer requires sudo privileges, thus enabling an easier and more secure module install.

There's nothing keeping one from installing the modules in the system space, using `sudo`, if they do choose.
