### ISSUE TITLE
Type in postgressql/sq/CreateTables.sql

### ISSUE THREAD

**Issue by MarkInNVA** [philipmat/discogs-xml2db#128]
Hi, 
Don't know if this is the proper way of letting you know of problems, but there is a comma on the last field of  'CREATE TABLE release_track ( ... track_id        text, );' (line 176) of 'postgresql\sql\CreateTables.sql'  that breaks the script for me. 

I also could not change from schema public on the 'postgresql\postgresql.conf' file, it seemed to have no effect on the CreateTables.sql script.

I ended up creating a new database and using public. Great tools, fun DB! 

Thanks,
Mark

**Comment by philipmat** [comment]
I believe that was fixed with this commit: https://github.com/philipmat/discogs-xml2db/commit/a3830fee0ce9c0d0a469546052a6f552d9fca241

Do you perchance have a version that's not up-to-date?

**Comment by philipmat** [comment]
Reopen and re-closed with commit https://github.com/philipmat/discogs-xml2db/commit/084434ae4f6cb2db6c279022950864d19b0c517a
