### ISSUE TITLE
Table release should be prefixed with database name

### ISSUE THREAD

**Issue by florisverstegen** [philipmat/discogs-xml2db#145]
When running this on Windows 10 with MySQL 8.4 I had a SQL Syntax issue when importing the release.csv file. It looks like table name release is throwing MySQL off as this is a reserved keyword (https://dev.mysql.com/doc/refman/8.4/en/keywords.html).
When prefixing the SQL code with the databasename it works fine.

**Comment by philipmat** [comment]
You probably want back-ticks: 
```
insert into `release` ...
```
