### ISSUE TITLE
It's normal? 

### ISSUE THREAD

**Issue by pablo-reyes-cabrera** [philipmat/discogs-xml2db#147]
Hi. I am applying foreign keys through the following command : mysql/exec_sql.sh < mysql/AssignForeignKeys.sql
The process has been running for 24 hours and is still not finished. Is this normal (MacBook Pro m2 32GB)? The process in the activity monitor shows a high % of CPU usage.

thanks in advance,  

Pablo Reyes

**Comment by philipmat** [comment]
It may be. It's a very large dataset...
You could run `SHOW FULL PROCESSLIST;` and see what MySQL processes are taking place
