### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by philipmat** [philipmat/discogs-xml2db#15]
Should have a way to test that new discogs XML releases do not break the parsing.

**Comment by pfouque** [comment]
Why not using Travis.
I didn't found any restriction on build duration.
So why not trying to stream gzip content to handlers and verifying it does not raise any errors ?

This is an example, just need to automate latest dump url

```

import unittest
from gzip import GzipFile
from urllib.request import urlopen

import xml.sax

from discogsmasterparser import MasterHandler
from jsonexporter import JsonConsoleExporter

from model import ParserStopError

class TestMasterHandler(unittest.TestCase):

    def test_parse_first(self):
        parser = xml.sax.make_parser()
        parser.setContentHandler(
            MasterHandler(
                JsonConsoleExporter(None),
                stop_after=0,
                ignore_missing_tags=True
            )
        )
        parser.parse(
            GzipFile(fileobj=urlopen(
                "http://discogs-data.s3-us-west-2.amazonaws.com/data/discogs_20170201_masters.xml.gz"
            ))
        )

if __name__ == '__main__':
    unittest.main()

```

**Comment by philipmat** [comment]
That'd be great!

However, when I wrote this bug, I was encountering two classes of errors. One would be discogs changing the structure of the export file - I think this would be able to catch some of that; the second, more subtle, is them experimenting with new features which would only show on newer entries, and those tend to be towards the end of the file. :(

But either way, we should start adding TravisCI into the process and then start writing tests for when we run into problems.

BTW, Pascal - if you plan on being involved more with the project, even if it's just on a temporary basis, I'd be more than happy to add you to the repo contributors.

**Comment by philipmat** [comment]
Travis CI added, but given the size of the dump files it's not feasible to use a free service to provide full integration testing.
