### ISSUE TITLE
Use Postgres Copy to get the data into Postgres

### ISSUE THREAD

**Issue by ijabz** [philipmat/discogs-xml2db#35]
Import of the release data is slow, not least because it is processing each record one by one sequentially adding them into the database. So I think the bottleneck is in the code the database could cope with multiple statements being fired at the same time. 

I think code could be speedup by parallelizing the import of the data, I wonder if just manually splitting the file into three chunks and running import on the three files in parallel would work.

**Comment by ijabz** [comment]
My work with acousticbrainz has convinced me the correct way to import the data is as follows.

The parser script should not attempt to run INSERT sql statements for each new record, instead it should write the data to a csv file (one file per table). Then at the end of the processing use Postgres Copy to copy the csv files into the database. The first stage will be much quicker because now just writing to a file rather than creating sql statements, checking db constraints etc, and this last stage will take a matter of minutes (see mbslave for comparison) . The total process should now take less than an hour compared to about 12 hours currently.

**Comment by philipmat** [comment]
If Postgres can import JSON, then perhaps we could make a single exporter that could be used by both the mongo and pg importers.

**Comment by ijabz** [comment]
Postgres can import json but the data will remain as json within the database rather as proper relational data,which is not terribly useful when trying to do queries across data, and would be totally incompatible with our existing discogs db schema.

However converting are existing code to write data to file and then COPY to database instead of direct INSERT into database is not actually that difficult. Its only difficult at all for me because I dont really know how to code in Python.

**Comment by philipmat** [comment]
Few ideas on making the import faster:
1. transaction bracket at file level (I think right now transaction bracketing is db op)
2. use the [COPY bulk insert](http://www.postgresql.org/docs/current/interactive/sql-copy.html) approach
3. since DB ops are slower than the SAX parsing, perhaps [splitting the DB inserts](https://wiki.python.org/moin/ParallelProcessing) into their own process (or processes)

**Comment by philipmat** [comment]
I took the cheap way out first and tried prepared statements (just the artists). Here's my code:
```python
def storeArtist(self, artist):
    if not self.good_quality(artist):
        return

    if not hasattr(self, 'artist_sql'):
        self.artist_sql = "PREPARE insert_into_artist AS INSERT INTO artist " \
                     "(id, name, realname, urls, namevariations, aliases, releases, profile, members, groups, data_quality) " \
                     "VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)"
        self.artist_plan_sql = "EXECUTE insert_into_artist (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

        self.artist_images_sql = "PREPARE insert_into_artist_images AS " \
                                 "INSERT INTO artists_images(type, height, width, image_uri, artist_id) " \
                                 "VALUES($1, $2, $3, $4, $5)"
        self.artist_images_plan_sql = "EXECUTE insert_into_artist_images (%s, %s, %s, %s, %s)"
        self.cur.execute(self.artist_sql)
        self.cur.execute(self.artist_images_sql)

    values = [artist.id,
              artist.name,
              artist.realname,
              artist.urls,
              artist.namevariations,
              artist.aliases,
              [],
              artist.profile,
              artist.members,
              artist.groups,
              artist.data_quality]
    #print query
    try:
        self.execute(self.artist_plan_sql, values)
    except PostgresExporter.ExecuteError, e:
        print "%s" % (e.args)
        return

    for img in artist.images:
        self.execute(self.artist_images_plan_sql, (img.imageType,img.height, img.width, img.uri, artist.id))
```

No significant improvement; with ` time python discogsparser.py -o pgsql -p "host=localhost dbname=discogs_py user=philip" -i ~/Downloads/discogs/discogs_20150501_artists.xml `:
- *Before*: real 17m9.612s  user 7m29.950s  sys 2m0.809s
- *After*: real 17m18.490s  user  7m46.640s  sys 2m0.120s

I'll try the `COPY` version next.

**Comment by ijabz** [comment]
So the way I see it working with COPY you need to change the code so that every insert into a different table instead writes the data to a seperate csv file, so you would have one artist.csv file, one artists_images.csv ecetera. Then once artist.xml has been fully processed you would run one COPY for each table, this second stage will just takes a few minutes (it is what mbslave does for musicbrainz database) so assuming the first stage is much faster than the current process the total time taken should be significantly quicker.

**Comment by philipmat** [comment]
I'm thinking about introducing a CSV or TextExporter that will produce
several files (Artists would have 2: artist and artists_images) and pair
that with an import script.

I'll do it for Artist and see what timings we get.

**Comment by systems-rebooter** [comment]
Hey @ijabz just curious - are storing dumps  in json like-style  in postgres or in native one? 

Sidenote: json feature postgres introduced recently sounds very awesome, but i didn't have much time to play with it.

**Comment by philipmat** [comment]
PG's COPY function produces these tab-separated files (also CSV, but I
don't want to mess with that) with a little bit of special formatting
inside.
That's basically what we'll produce as well.

**Comment by ijabz** [comment]
systems-rebooter no I don't use the json, Im not very ethusiastic about the json support since I don't think it would work  when trying to construct queries over the tables for lots of rows, its more for just drilling down to get the information for a particular row. Trying to combine drilling down with relational queries is unlikely to perform at all well.

To put it another way if you want to say return all the details for a particular release then returning the data as json rather than sql columns may be okay. But if you want to say return all the releases with a particular catanologno you yo  need that catalog to be within its own column in db not just embedded within a json object.

**Comment by ijabz** [comment]
This is the approach taken by this fork of discogs-xml actually - https://github.com/alvare/discogs2pg

**Comment by ijabz** [comment]
Closed because this is implemented as RedApples branch discussed on https://github.com/philipmat/discogs-xml2db/issues/65
