### ISSUE TITLE
invalid token of release xml file when loading into PostgreSQL

### ISSUE THREAD

**Issue by cnyingliu** [philipmat/discogs-xml2db#51]
I am loading the xml files into the PostgreSQL. I downloaded 20140803 version and 20140701 version. Both of them I met errors when loading the release xml file. 

For 20140803 version:
xml.sax._exceptions.SAXParseException: discogs_20140803_releases.xml:53155:784: not well-formed (invalid token)

For 20140701 version: 
xml.sax._exceptions.SAXParseException: discogs_20140701_releases.xml:3763466:690: not well-formed (invalid token)

Which version of discogs did you load into PostgreSQL successfully? 

Thank you,
Ying

**Comment by ijabz** [comment]
closed because works fine with later versions of xml
