### ISSUE TITLE
Error when trying to import discogs master file

### ISSUE THREAD

**Issue by analogline** [philipmat/discogs-xml2db#52]
Got this output, and import stop, after trying to import the 20141001 release data.

Traceback (most recent call last):
  File "discogsparser.py", line 241, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 236, in main
    parseMasters(parser, exporter)
  File "discogsparser.py", line 171, in parseMasters
    parser.parse(master_file)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 307, in end_element
    self._cont_handler.endElement(name)
  File "/home/<username>/Discogs_Importer/discogs-xml2db-master/discogsmasterparser.py", line 173, in endElement
    self.exporter.storeMaster(self.master)
  File "/home/<username>/Discogs_Importer/discogs-xml2db-master/postgresexporter.py", line 323, in storeMaster
    (img.uri, img.image_type, master.id))
AttributeError: ImageInfo instance has no attribute 'image_type'

**Comment by PattMayne** [comment]
Has this been fixed yet? I just had the same error today. It worked last month but this time it crashed.

**Comment by ijabz** [comment]
no it has not

**Comment by philipmat** [comment]
Can you try running it with --ignore-unknown-tags and see if that works?


• mobilized •

**Comment by PattMayne** [comment]
I'll try that tomorrow. I tried changing the code so that "image_type" became "imageType" (because that seemed to be the appropriate corresponding term from earlier in the code), but then I got this error:

TypeError: not all arguments converted during string formatting

So I'll try it with the --ignore-unknown-tags  idea...

is there any way for me to just pick up where it failed? Or do I need to start the whole thing again?

**Comment by philipmat** [comment]
Sadly there's no good way to "resume" 😔


• mobilized •

**Comment by PattMayne** [comment]
After another 8 hours of processing I got the same error. I want to tweak the code and maybe help you find a fix that works for everyone, but I don't want to spend 8 hours waiting for the crash lol.

I'll try something else tomorrow. In the meantime I'm wide open for ideas. Is there any way I can just tell it to skip the images? I need the masters, but I don't need the master images.

**Comment by philipmat** [comment]
We definitely appreciate you wanting to fix the code. Here's an idea to help testing: find the offending node in the file and move it either at the beginning or in a file by itself, then run against that file.

**Comment by ijabz** [comment]
Now fixed and merged into master
