### ISSUE TITLE
md5 Can't be Created

### ISSUE THREAD

**Issue by systems-rebooter** [philipmat/discogs-xml2db#55]
Hello,

Looks like md5 files like described in README, can't be created. 
```
$ discogsparser.py -i -o mongo -p "file:///tmp/discogs/?uniq=md5" -d 20111101 
# this results in 2 files creates for each class, e.g. an artists.json file and an artists.md5 file
```

I'm using  Python 2.7.5

**Comment by philipmat** [comment]
Do you have an error message or anything that could help us further troubleshoot this?

**Comment by systems-rebooter** [comment]
Hey! Thanks for quick response. 

You can find below my stdout. discogs-parser is completed successfully.  
Is there any ability to make it more verbose? 

```
$ time discogsparser.py -i -o mongo -p "file:///tmp/discogs/?uniq=md5" discogs_20141101_releases.xml
Namespace(data_quality=None, date=None, file=['discogs_20141101_releases.xml'], ignore_unknown_tags=True, n=None, output='mongo', params='file:///tmp/discogs/?uniq=md5')

real	171m39.703s
user	166m46.727s
sys	4m35.317s
$
```
```
$ ls -lah /tmp/discogs
total 31027912
drwxr-xr-x   6 root  wheel   204B Mar 16 01:23 .
drwxrwxrwt  12 root  wheel   408B Mar 16 11:14 ..
-rw-r--r--   1 root  wheel     0B Mar 16 01:23 artists.json
-rw-r--r--   1 root  wheel     0B Mar 16 01:23 labels.json
-rw-r--r--   1 root  wheel     0B Mar 16 01:23 masters.json
-rw-r--r--   1 root  wheel    15G Mar 16 01:23 releases.json
$
```

Thanks!

**Comment by systems-rebooter** [comment]
Hey,

Did you have a chance to look on this issue? 

Thanks!

**Comment by philipmat** [comment]
No, I'm sorry - I haven't had a chance. I was hoping that you'd get some sort of (explicit) error message, but that doesn't appear to be the case. I was hoping to find some time this weekend to look into it.

**Comment by systems-rebooter** [comment]
Thanks @philipmat Will be waiting for the update. `md5` is very valuable feature for `--upsert` performing. Thanks a lot!

**Comment by philipmat** [comment]
The issue was due to the query string no longer being included in `urlparse -> u.path` property. It's now in `u.query`.
I've tested only with the *discogs_20150301_labels.xml* file, but the *md5* gets generated properly now.

Thanks for reporting it and thank you in advance for testing with the rest of the files.

**Comment by systems-rebooter** [comment]
Awesomeness! Thanks much @philipmat
