### ISSUE TITLE
discogsparser.py doesn't run

### ISSUE THREAD

**Issue by buremba** [philipmat/discogs-xml2db#6]
I created a database in postgresql and imported database schema. And I tried to run discogsparser.py with following command:

``` python
python discogsparser.py -o pgsql -p "host=localhost dbname=discogs user=[user] password=[pass]" discogs_20120501_releases.xml.gz
```

Also I tried json format but the result doesnt' change. I'm getting something like this:

``` python
Namespace(data_quality=None, date=None, file=['discogs_20120501_releases.xml.gz'], ignore_unknown_tags=False, n=None, output='pgsql', params='host=localhost dbname=discogs user=[user] password=[pass]')
```

and discogsparser.py stop working without any exception.

**Comment by fbm2p** [comment]
Hi, 
same problem here, when trying to import the data with following commands:

`python discogsparser.py -n 20 -o json -d discogs_20141201_artists.xml`

I encounter following problem:

`Namespace(data_quality=None, date='discogs_20141201_artists.xml', file=[], ignore_unknown_tags=False, n=20, output='json', params=None)`
 
Also, parsing all files for a given monthly dump with export to a PostgreSQL database:
`python discogsparser.py -o pgsql -p "dbname=discogs user=discogs" -d 20141201`

results in following output:

`Namespace(data_quality=None, date='20141201', file=[], ignore_unknown_tags=False, n=None, output='pgsql', params='dbname=discogs user=discogs')
Traceback (most recent call last):
  File "C:\Discogs\discogs-xml2db-master\discogs-xml2db-master\discogsparser.py", line 241, in <module>
    main(sys.argv[1:])
  File "C:\Discogs\discogs-xml2db-master\discogs-xml2db-master\discogsparser.py", line 234, in main
    parseLabels(parser, exporter)
  File "C:\Discogs\discogs-xml2db-master\discogs-xml2db-master\discogsparser.py", line 113, in parseLabels
    parser.parse(label_file)
  File "C:\Python27\lib\xml\sax\expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Python27\lib\xml\sax\xmlreader.py", line 125, in parse
    self.close()
  File "C:\Python27\lib\xml\sax\expatreader.py", line 220, in close
    self.feed("", isFinal = 1)
  File "C:\Python27\lib\xml\sax\expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "C:\Python27\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: discogs_20141201_labels.xml:1:0: no element found`

**Comment by philipmat** [comment]
From this:
```
xml.sax._exceptions.SAXParseException: discogs_20141201_labels.xml:1:0: no element found
```

I would venture to guess that there's a problem with the xml (make sure it's uncompressed, make sure it's a valid file, etc)

**Comment by fbm2p** [comment]
Thanks @philipmat for the hint. However, I've verified the gz files with SHA-256 checksum checker and it seems they're OK. Same applies to XMLs, which are input files for the ```discogsparser.py```
Do you think it can have something to do with ```fix-xml.py``` and fixing of control characters and root tags in those XML files?
