### ISSUE TITLE
Tracks of a release extraartist not being exported

### ISSUE THREAD

**Issue by pedro-otero** [philipmat/discogs-xml2db#71]
The extraartists in a release retrieved from Discogs API have an extraartists array, on which each item contains a "tracks" value. Those values, that are ok on the dump XMLs, are not exported to JSON.

One example:
Release with id 770236

![image](https://cloud.githubusercontent.com/assets/15470487/19016779/db02e222-87e9-11e6-80dd-11c1abc0181b.png)

But when exporting the dump xml all I get is:

![image](https://cloud.githubusercontent.com/assets/15470487/19016789/0c84b460-87ea-11e6-9ba5-57b411486dba.png)

This happens on all records since the query:

`
db.getCollection('releases').find({
        extraartists: {$elemMatch: {tracks:{$exists:true}}}
    })
`
returns no matches

In the release example I showed in the images the tracks value is this:

`<tracks>1, 3 to 10, 14</tracks>`

**Comment by pfouque** [comment]
I just tested this, and I didn't reproduced it.
Could you confirm this problem persists? or we can close this issue ?

**Comment by philipmat** [comment]
Closing issue as per @pfouque testing.
