### ISSUE TITLE
crash while importing latest dump into postgresql: format qty out of range 

### ISSUE THREAD

**Issue by berz** [philipmat/discogs-xml2db#73]
discogs-xml2db crashes when importing the [latest release XML](http://discogs-data.s3-us-west-2.amazonaws.com/data/discogs_20161101_releases.xml.gz) into Postgresql.

This seems to be caused by the album [One Vigintillion(10^63) Songs](https://www.discogs.com/Peculiar-Surely-Goodness/release/8262262) by Tetsuro (3). The album contains 10⁶³+1 five-second tracks and has the following format: 

`Format:
1000000000000000000000000000000000000000000000000000000000000001 × File, MP3, Album, Mono, 32 kbps`

This release format is present in the xml dump as such:

```xml
<release id="8262262" status="Accepted">
  [...]
  <formats>
    <format name="File"
    qty="1000000000000000000000000000000000000000000000000000000000000001"
    text="32 kbps">
      <descriptions>
        <description>MP3</description>
        <description>Album</description>
        <description>Mono</description>
      </descriptions>
    </format>
  </formats>
  [...]
</release>
```

The importer crashes when INSERTing this release format since of the huge `qty` attribute is too large to be stored as an integer.
```
Error executing: INSERT INTO releases_formats(release_id, position, format_name,
qty, descriptions) VALUES(8262262,1,'File',
'1000000000000000000000000000000000000000000000000000000000000001',ARRAY['MP3', 
'Album', 'Mono']);
"1000000000000000000000000000000000000000000000000000000000000001" is out of 
range for type integer
 ```

full error output:

```
	Error executing: INSERT INTO releases_formats(release_id, position, format_name, qty, descriptions) VALUES(8262262,1,'File','1000000000000000000000000000000000000000000000000000000000000001',ARRAY['MP3', 'Album', 'Mono']);
	Traceback (most recent call last):
	  File "../discogs-xml2db-master/discogsparser.py", line 241, in <module>
	    main(sys.argv[1:])
	  File "../discogs-xml2db-master/discogsparser.py", line 235, in main
	    parseReleases(parser, exporter)
	  File "../discogs-xml2db-master/discogsparser.py", line 142, in parseReleases
	    parser.parse(release_file)
	  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
	    xmlreader.IncrementalParser.parse(self, source)
	  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
	    self.feed(buffer)
	  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
	    self._parser.Parse(data, isFinal)
	  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 307, in end_element
	    self._cont_handler.endElement(name)
	  File "/media/sf_Desktop/Discogs-update/discogs-xml2db-master/discogsreleaseparser.py", line 309, in endElement
	    self.exporter.storeRelease(self.release)
	  File "/media/sf_Desktop/Discogs-update/discogs-xml2db-master/postgresexporter.py", line 217, in storeRelease
	    self.execute(query, (release.id, fmt_order, fmt.name, fmt.qty, fmt.descriptions))
	  File "/media/sf_Desktop/Discogs-update/discogs-xml2db-master/postgresexporter.py", line 67, in execute
	    raise PostgresExporter.ExecuteError(e.args)
	postgresexporter.ExecuteError: value "1000000000000000000000000000000000000000000000000000000000000001" is out of range for type integer
	LINE 1: ..._name, qty, descriptions) VALUES(8262262,1,'File','100000000...
```

**Comment by philipmat** [comment]
Guess we'll have to change the column type - @berz would you mind submitting a PR?

**Comment by berz** [comment]
Changing the column type indeed looks like the way to go. If discogs supports albums with a vigintillion tracks then so should we. 

Looking at the [types supported by postgresql](https://www.postgresql.org/docs/9.4/static/datatype-numeric.html) it seems we should use the numeric type (aka the decimal type) since it is the only exact number type large enough. There is a warning in there saying that doing arithmetic on this type is very slow compared to the integer types though, I hope this is not an issue in our case.

I changed the column type to NUMERIC(100, 0) -- an integer with a maximum of 100 digits -- and am importing the latest releases xml dump at the moment. I will submit a PR if this fixes the issue without causing any new problems.

**Comment by ijabz** [comment]
Ive made change on my fork 

qty 		NUMERIC(100, 0),

and it did indeed work

**Comment by berz** [comment]
I forgot to send the PR, here it is.
