### ISSUE TITLE
Mac `get_latest_dump` platform issue

### ISSUE THREAD

**Issue by rikola** [philipmat/discogs-xml2db#74]
The `ack-grep` package on OSX is called `ack`. This causes the script to error out unless you remove the `-grep` from this command in the script. Just an FYI to those using Macs.

**Comment by philipmat** [comment]
Thank you @rikola.

We should be really using `grep` since it's available by default on all platforms.

**Comment by rikola** [comment]
Nice work. Thanks!

**Comment by rikola** [comment]
Actually when running the script now on the latest commit it does not seem to do anything at all. There is nothing coming on `stdout` and no files being added to the directory. Not sure what the cause is there.

**Comment by rikola** [comment]
For macs it works with just `ack` but thats obviously not Linux compatible since that package is `ack-grep`

**Comment by philipmat** [comment]
@rikola - could you confirm it works now?

**Comment by rikola** [comment]
Works perfectly now. Thanks!
