### ISSUE TITLE
URL field splitting for social network sites

### ISSUE THREAD

**Issue by rikola** [philipmat/discogs-xml2db#75]
Hello.

Would you be interested in me submitting a PR that can split the URL array for artists into separate columns such as `facebook_url`, `twitter_url`, etc. I have implemented this for my custom use case but I feel like it could be a useful option for those who need these specific values.

**Comment by rikola** [comment]
Heres the file for an example [URL Splitter](https://github.com/rikola/mybandsource-parser/blob/master/importer.py)

**Comment by philipmat** [comment]
I'd honestly prefer to have a separate table of links; a KVP-type table where the key is the media platform (e.g. FB, IG, etc) and the value is the URL. That should make it easy to extend at any time  without any schema changes. 

Second in preferences would be to store this dictionary of platform-URL as JSON in a single field in the artist table. Since PG can deal with JSON this would fulfill both the querying ability as well as the extensibility one. 

what do you think?

**Comment by rikola** [comment]
Yeah that is probably a more extensible idea. Not sure how to implement that in the other DB platforms though.

**Comment by philipmat** [comment]
Implement it for PG, don't worry about Mongo.

**Comment by pfouque** [comment]
Hi, 

it's a cool feature but aren't you afraid that everybody will want to add the service he needs?

What make the strength of this repository is its simplicity, it only converts, and does not interpret results.
i'm afraid that if you begin to implement interpretation features like this, your repository will become too big and difficult to maintain.

I understand what @rikola  need (i do something similar and much more), but perhaps something more generic will be to give a way for user to define some kind of postprocess.

I dunno how at the moment but there is an interesting fork which turns this project into a python module, perhaps it's the first step to give ability to inherit and override.

**Comment by philipmat** [comment]
Good point, @pfouque. I assumed that the entries for social media contacts are already in the data-dumps, in which case we're only adding info that's already there. Is this not the case, @rikola?

(Sorry, I'm not currently able to look at the artist dump)

**Comment by pfouque** [comment]
What i understood is extracting some social media url from the list of urls, but I know some profiles have multiple url for Twitter and Facebook.

**Comment by ijabz** [comment]
>>I'd honestly prefer to have a separate table of links; a KVP-type table where the key is the media platform (e.g. FB, IG, etc) and the value is the URL. That should make it easy to extend at any time without any schema changes.

This is the case with speedup commit, see artist_url table

**Comment by ijabz** [comment]
Well perhaps not the case we dont have a media platform field but the data is now stored in a proper table (is, artistid, url) rather than just  using an array. Since it is now  a table should be easy for users to extract data as required into another table for particular use case.

**Comment by philipmat** [comment]
Closing this issue as we haven't made any progress on it and there may be a better approach to implementing this: for example a database view.
