### ISSUE TITLE
Discogs dumps storage has changed

### ISSUE THREAD

**Issue by pfouque** [philipmat/discogs-xml2db#77]
It seems Discogs changed the way dumps are stored.
There is no more current year dumps available on main page
All dumps are stored in a per year directory, even latest.

**Comment by pfouque** [comment]
I have a fix for that issue but it also contains some small changes : 
- replace "print" function to be PY3 compatible
- fix file containing mixed tab and space indentation

Can i do a non-atomic pull request (even if i shouldn't)

**Comment by philipmat** [comment]
I'm more than happy to accept a PR that pushes towards PY3 compatibility. For the purpose of historical identification, I'd prefer that it is the only thing in the patch, but I think I honestly care more about moving towards PY3 than polluting the history, if you cannot separate the two.

What's your take @ijabz ?

**Comment by pfouque** [comment]
There is already a pull request containing Python3 compatibility and fixed file containing mixed tab and space indentation (which is not supported by python3).
So if you merge it, fix for this issue will be easier to merge

**Comment by ijabz** [comment]
@philpmat I have sympathies with @pfouque as I find git very difficult to use, and I have no view regarding PY2/PY3 so I would lean towards just do it.
