### ISSUE TITLE
Fix pep8 and Py3 build errors

### ISSUE THREAD

**Issue by philipmat** [philipmat/discogs-xml2db#78]
With <https://github.com/philipmat/discogs-xml2db/commit/928ea4e77c482d87836a9e8d75b7db003dd98893> *discogs-xml2db* has minimal Travis CI integration: currently pep8 and python compilation (for syntax checking).

The build [currently fails](https://travis-ci.org/philipmat/discogs-xml2db/jobs/203526675) because:
- of a multitude of pep8 errors (I've ignored tabs, but there's a good deal of others)
- invalid Py3 syntax

```
The command "pep8 *.py" exited with 1.
0.18s$ python -m py_compile *.py
  File "postgresexporter.py", line 49
    except psycopg2.Error, e:
                         ^
SyntaxError: invalid syntax
```

**Comment by philipmat** [comment]
Should run against pep 1.7

**Comment by pfouque** [comment]
🥇
