### ISSUE TITLE
Tracklist and subtracks

### ISSUE THREAD

**Issue by redapple** [philipmat/discogs-xml2db#83]
When adding unittests in https://github.com/philipmat/discogs-xml2db/pull/82 , I noticed a bug on parsing tracklists with subtracks.

It appears that the release parser only returns the last subtrack for all subtracks of a track:

- e.g. https://www.discogs.com/release/779, only tracks "1b", "2c", "3b", "4b"
  this is what pgdump exporter output (redacted):

```
INSERT INTO track(release_id, title, duration, position, track_id, trackno)
    VALUES
        (779, 'Ice', '', '1b', '38ec01fe-70e5-4237-9007-ec461ab4c258', 1),
        (779, 'Part 3', '', '2c', '6068819a-addb-4148-ba88-76367e29c55e', 2),
        (779, 'Part 2', '', '3b', '96b4e627-4d20-4494-8185-21689e2c6e0e', 3),
        (779, 'Part 2', '', '4b', '55ba523f-9999-40cf-aef5-86ed77e85743', 4)
```

- another example, https://www.discogs.com/release/870, the parser only finds 1 track, the 4th subtrack "Vocal Reprise"

Question for users: How do we want to fix this?
- Are all subtracks needed?
- should the parser only consider the parent track?
- should the parser extract the parent and the subtracks? there's currently no hierarchy in the `track` table

**Comment by redapple** [comment]
This is a sample of releases with subtracks (from the 20160901 dump): https://gist.github.com/redapple/e0f34de9c289f7c8def56d9f8d69b8c3

**Comment by philipmat** [comment]
I want to just chime in and say I have no opinion on this.  
I will accept a patch that either discards any sub-track info or that imports them.

Either way, it should not break the existing functionality (don't forget about Mongo too).
