### ISSUE TITLE
Every releases.l_artist is null in MongoDB

### ISSUE THREAD

**Issue by drone1** [philipmat/discogs-xml2db#85]
I imported with the commands:
./discogsparser.py -o mongo -p "mongodb://127.0.0.1:3001/meteor" discogs_20170901_artists.xml
./discogsparser.py -o mongo -p "mongodb://127.0.0.1:3001/meteor" discogs_20170901_releases.xml
./discogsparser.py -o mongo -p "mongodb://127.0.0.1:3001/meteor" discogs_20170901_masters.xml
./discogsparser.py -o mongo -p "mongodb://127.0.0.1:3001/meteor" discogs_20170901_labels.xml
in parallel, to utilize 4 cores. 

Initially I used -d 20170901 to import everything, and it was so unbelievably slow I killed it, wiped my db and started from scratch. 

I see that I do indeed have an index based on releases.l_title & l_artist, but every l_artist is null. Seems wrong.

Did I mess up w/ my parallelized import commands?

I also see that there is releases.artistJoins. I created an index on this, and this has helped me get off the ground, but I'm also noticing that all releases.images have only widths but no actual "uri" fields. And also no youtube_videos (which the WebAPI returns in each release IIRC). Any suggestions? Perhaps I should have gone the JSON route? :(

**Comment by ijabz** [comment]
image uris are no longer available in the Discogs downloads, we store the sizes so you know if it is worth the bother of retrieving the images from Discogs itself

**Comment by drone1** [comment]
And l_artist is no longer valid I guess? I created an index on
artiatJoins.artist_id and that's been good enough.

**Comment by drone1** [comment]
I wish there were a way to get a dump of the images by the way. Man that 60
requests per minute is just the most annoying thing ever.
