### ISSUE TITLE
provide progress indicator while importing

### ISSUE THREAD

**Issue by berz** [philipmat/discogs-xml2db#88]
Importing the discogs dumps takes several hours so it would be useful to provide some indication of progress during this process. At the moment new users have no idea how long it takes and could be wondering if the program is stuck. This would also help existing users compare the processing speed of different machines or configurations.

I wrote a script to provide me with this information. It looks up the xml file the program is reading from and the position within this file to provide the output below. The script is available at https://github.com/berz/discogs-xml2db/blob/progress-indicator/showprogress.sh but will only run on linux as it uses the /proc file system.

	file: /space/dumps/discogs_20171001_releases.xml
	progress:          14.066 %
	current position:   4895899648 B
	file size:         34806214917 B
	started at:        2017-10-29 16:36:07
	estimated end:     2017-10-30 03:47:55

**Comment by philipmat** [comment]
Do you know if it works on Mac? (I'm not at a point where I can test is) 
If not, could you be so kind as to add an `if` based on `uname` and exit with a note saying it only works on Linux systems?

And could you send a PR for it? :)

**Comment by ijabz** [comment]
The latest version of get_latest_dump.sh fails for me on Ubuntu and I have to go back to an earlier version.

**Comment by berz** [comment]
@ijabz did you mean to post that reply in one of the other issues?

Regarding this issue: the code in the speedup folder does show a progress indicator so this issue can be closed if the speedup version replaces the old code.

**Comment by ijabz** [comment]
I commented on this issue because _improved on script with aria2c#93_ linked to it, but I may have done this wrong.

**Comment by ijabz** [comment]
Closed because done (and my comments are misleading apply to a different issue)
